create schema if not exists private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  student_id text not null default '',
  username text not null default '',
  profile_picture text not null default '',
  education_level text not null default '',
  class_grade text not null default '',
  subjects text not null default '',
  university_year text not null default '',
  course_program text not null default '',
  role text,
  institution text not null default '',
  faculty text not null default '',
  department text not null default '',
  teaching_level text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text;
alter table public.profiles add column if not exists institution text not null default '';
alter table public.profiles add column if not exists faculty text not null default '';
alter table public.profiles add column if not exists department text not null default '';
alter table public.profiles add column if not exists teaching_level text not null default '';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_role_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_role_check
      check (role is null or role in ('high_school_student', 'university_student', 'teacher'));
  end if;
end;
$$;

alter table public.profiles enable row level security;

drop policy if exists "Students can read their own profile" on public.profiles;
create policy "Students can read their own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Students can insert their own profile" on public.profiles;
create policy "Students can insert their own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "Students can update their own profile" on public.profiles;
create policy "Students can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function private.protect_profile_role()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.role := old.role;
  return new;
end;
$$;

drop trigger if exists protect_profile_role on public.profiles;
create trigger protect_profile_role
before update on public.profiles
for each row execute function private.protect_profile_role();

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  lesson_id integer not null,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lesson_progress_user_course_lesson_key unique (user_id, course_id, lesson_id)
);

create index if not exists lesson_progress_user_course_idx
  on public.lesson_progress (user_id, course_id);

alter table public.lesson_progress enable row level security;

drop policy if exists "Students can read their own lesson progress" on public.lesson_progress;
create policy "Students can read their own lesson progress"
  on public.lesson_progress for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Students can insert their own lesson progress" on public.lesson_progress;
create policy "Students can insert their own lesson progress"
  on public.lesson_progress for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Students can update their own lesson progress" on public.lesson_progress;
create policy "Students can update their own lesson progress"
  on public.lesson_progress for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Students can delete their own lesson progress" on public.lesson_progress;
create policy "Students can delete their own lesson progress"
  on public.lesson_progress for delete
  to authenticated
  using (auth.uid() = user_id);

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (
    id, full_name, role, institution, faculty, department, teaching_level,
    class_grade, education_level, subjects, university_year, course_program
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case
      when new.raw_user_meta_data ->> 'role' in (
        'high_school_student', 'university_student', 'teacher'
      )
      then new.raw_user_meta_data ->> 'role'
      else null
    end,
    coalesce(new.raw_user_meta_data ->> 'institution', ''),
    coalesce(new.raw_user_meta_data ->> 'faculty', ''),
    coalesce(new.raw_user_meta_data ->> 'department', ''),
    coalesce(new.raw_user_meta_data ->> 'teaching_level', ''),
    coalesce(new.raw_user_meta_data ->> 'class_grade', ''),
    coalesce(new.raw_user_meta_data ->> 'education_level', ''),
    coalesce(new.raw_user_meta_data ->> 'subjects', ''),
    coalesce(new.raw_user_meta_data ->> 'university_year', ''),
    coalesce(new.raw_user_meta_data ->> 'course_program', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

-- Profile role is descriptive data only. It must not be used as authorization.
-- Authorization will use Supabase app metadata/custom claims when RBAC is added.
