create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  student_id text not null default '',
  username text not null default '',
  profile_picture text not null default '',
  education_level text not null default '',
  class_grade text not null default '',
  subjects text not null default '',
  university_year text not null default '',
  course_program text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "Students can read their own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

create policy "Students can insert their own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "Students can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  lesson_id integer not null,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lesson_progress_user_course_lesson_key unique (user_id, course_id, lesson_id)
);

create index if not exists lesson_progress_user_course_idx
  on public.lesson_progress (user_id, course_id);

alter table public.lesson_progress enable row level security;

create policy "Students can read their own lesson progress"
  on public.lesson_progress for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Students can insert their own lesson progress"
  on public.lesson_progress for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Students can update their own lesson progress"
  on public.lesson_progress for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Students can delete their own lesson progress"
  on public.lesson_progress for delete
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
